export const ExperiencesDict = [
  {
    id: 'professional',
    year: '2023',
    title: 'Cybersecurity',
    location: 'Bloomington',
    company: 'OmniSOC',
  },
  {
    id: 'professional',
    year: '2022',
    title: 'Master Data',
    location: 'Chicago',
    company: 'Oil-Dri',
  },
  {
    id: 'professional',
    year: '2022',
    title: 'Horgan Group',
    location: 'Newport Beach',
    company: 'Raymond James',
  },
  {
    id: 'academic',
    year: '2022',
    title: 'Private Tutor',
    location: 'Evanston',
    company: 'NU Tutors',
  },
  {
    id: 'academic',
    year: '2022',
    title: 'YW Tech Lab Tutor',
    location: 'Evanston',
    company: 'YWCA',
  },
  {
    id: 'professional',
    year: '2021',
    title: 'Operations and Supply Chain',
    location: 'San Diego',
    company: 'CorDX',
  },
  {
    id: 'philanthropic',
    year: '2021',
    title: 'Vaccine Runner and Observer',
    location: 'La Jolla',
    company: 'UCSD Health',
  },
  {
    id: 'philanthropic',
    year: '2021',
    title: 'Student Caller',
    location: 'San Diego',
    company: 'Serving Seniors',
  },
  {
    id: 'philanthropic',
    year: '2021',
    title: "International Women's Week Event Lead",
    location: 'La Jolla',
    company: 'UCSD ERC',
  },
  {
    id: 'philanthropic',
    year: '2020',
    title: 'Triton Tutor Volunteer Lead',
    location: 'La Jolla',
    company: 'UCSD Health',
  },
  {
    id: 'philanthropic',
    year: '2020',
    title: 'Office for Students with Disabilities Note Taker',
    location: 'La Jolla',
    company: 'UCSD',
  },
  {
    id: 'academic',
    year: '2020',
    title: 'Student Researcher',
    location: 'La Jolla',
    company: 'UCSD',
  },
  {
    id: 'philanthropic',
    year: '2020',
    title: 'International Students and Programs Representative',
    location: 'La Jolla',
    company: 'UCSD',
  },
  {
    id: 'philanthropic',
    year: '2020',
    title: 'Surgery Intern and Volunteer',
    location: 'Montebello',
    company: 'Beverly Hospital',
  },
  {
    id: 'academic',
    year: '2019',
    title: 'Writing Center Tutor',
    location: 'San Juan Capistrano',
    company: "St. Margaret's",
  },
  {
    id: 'professional',
    year: '2019',
    title: 'Technology Group Public Relations',
    location: 'Beijing',
    company: 'Haitang Group',
  },
  {
    id: 'academic',
    year: '2019',
    title: 'Private Tutor',
    location: 'Irvine',
    company: 'Easy A',
  },
  {
    id: 'professional',
    year: '2018',
    title: 'Events',
    location: 'Corona',
    company: 'LuLaRoe',
  },
  {
    id: 'academic',
    year: '2018',
    title: 'Orchestra Teacher Assistant',
    location: 'San Juan Capistrano',
    company: "St. Margaret's",
  },
  {
    id: 'academic',
    year: '2016',
    title: 'English Teacher',
    location: 'Taipei',
    company: 'Advent Taiwan',
  },
  {
    id: 'philanthropic',
    year: '2016',
    title: 'Director & Founder',
    location: 'Laguna Niguel',
    company: 'YMOC',
  },
];
