export const ProjectsDict = [
  { name: 'IoT Security', year: '2024' },
  { name: 'APT Generator', year: '2024' },
  { name: 'WildHacks', year: '2024' },
  { name: 'RecipeBot', year: '2023' },
  { name: 'Operations', year: '2023' },
  { name: 'TweetMining', year: '2023' },
  { name: 'WildHacks', year: '2023' },
  { name: 'ConnectedSpine', year: '2023' },
  { name: 'PhotoApp', year: '2022' },
  { name: 'PacMan', year: '2022' },
];

export const ProjectDetailsDict = [
  {
    name: 'IoT Security',
    year: '2024',
    github: null,
    website: null,
    about:
      'Our project embarks on a longitudinal study to evaluate the security evolution of IoT devices from lesser-known vendors, assessing whether previous vulnerabilities have been addressed in newer versions. By employing tools like Wireshark for network traffic analysis and encryption scrutiny, we aim to uncover changes in security measures over time, comparing current device security to past findings. This study not only identifies persistent security gaps but also explores the efficacy of open-source honeypots as interim solutions for detected vulnerabilities. Through a comprehensive analysis of selected IoT devices, including smart light bulbs and plugs, our research contributes valuable insights into the progression of IoT security practices, offering guidance for consumers and recommendations for vendors on enhancing device security. This endeavor underscores the critical need for ongoing scrutiny in the fast-evolving IoT landscape, aiming to bolster the overall security posture of emerging and existing IoT technologies.',
    role: "In this IoT security project, I focused on reviewing past security issues of IoT devices, especially Philips and Sengled smart bulbs, and conducted experiments to test their current software and encryption security. Using network analysis tools like Wireshark, I examined how these devices manage data security and encryption, comparing it with previous vulnerabilities. My role was essential in identifying improvements or ongoing weaknesses in the security protocols of these IoT devices, contributing valuable insights into the industry's progress in addressing security concerns.",
    skills: [
      'Wireshark',
      'Literature Review',
      'Network Traffic Analysis',
      'Encryption and Security Protocols Evaluation',
      'Comparative Security Assessment',
      'IoT Device Vulnerability Testing',
    ],
  },
  {
    name: 'APT Generator',
    year: '2024',
    github: 'https://github.com/kedarthiagarajan/APTGeneration',
    website: null,
    about:
      'Automated Generation of Advanced Persistent Threats (APTs) Utilizing Large Language Models (LLMs): This project aims to enhance cybersecurity defenses by constructing a comprehensive knowledge base of APT attack techniques and simulating real-world APT scenarios. Leveraging Large Language Models (LLMs), we generate tailored attack scripts based on established tactics, techniques, and procedures (TTPs) from MITRE and the Atomic Red Team. Our work not only broadens the understanding of APT methodologies but also provides a valuable platform for testing and improving defense systems. Through this initiative, we contribute to the development of more resilient cybersecurity mechanisms and offer an educational resource for the cybersecurity community.',
    role: "In our project focused on automating APT simulations with LLMs, I played a key role by setting up the Vagrant infrastructure for hosting Caldera agents, essential for testing our generated APT scenarios. Additionally, my contributions extended to leveraging LangChain and prompt engineering to develop Python scripts, enabling the automated generation of intricate attack commands. My work not only underpinned our experimental setup but also significantly advanced our project's goal of creating realistic cybersecurity threat simulations.",
    skills: [
      'Vagrant',
      'Caldera',
      'Python',
      'LangChain',
      'Virtualization',
      'Scripting',
    ],
  },
  {
    name: 'WildHacks',
    year: '2024',
    github: 'https://github.com/NUWildHacks/website2024',
    website: 'https://www.wildhacks.net/',
    about:
      'WildHacks 2024, Northwestern\'s premier overnight hackathon, provides a platform for students to hone their programming skills, collaborate on innovative projects, and immerse themselves in a learning-rich environment. To publicize WildHacks, we built a frontend client using TypeScript and React, designed to align with Major League Hacking (MLH) guidelines. This platform facilitates seamless participant registration, enabling competitors to access a custom dashboard. Here, they could not only submit their projects but also explore an array of projects showcased from previous years, fostering an ecosystem of inspiration and innovation. Embracing this year\'s theme, "Beyond the Books," we infused the website with a mystical book theme, creating an engaging, story-driven user experience that captivates and transports participants into a realm where coding intertwines with fantasy.',
    role: "As the Director of Technology for WildHacks 2024, I played a crucial role in setting up our project's foundation and leading our team through the development process. I organized and led both group and pair programming meetings, ensuring everyone worked together effectively. My role involved assigning tasks to team members based on their strengths, which helped us work efficiently. Following Major League Hacking (MLH) guidelines, I guided the team in building a frontend website that supports easy registration and project submissions for participants, all hosted on GitHub. This effort was key to making WildHacks an inclusive and innovative experience for all attendees.",
    skills: [
      'React',
      'TypeScript',
      'GitHub',
      'Project Management',
      'Google Analytics',
      'Team Leadership',
    ],
  },
  {
    name: 'RecipeBot',
    year: '2023',
    github: 'https://github.com/dyu222/ParsingProject',
    website: null,
    about:
      'The ParsingProject introduces a conversational agent, RecipeBot, designed to streamline culinary experiences through intelligent parsing of recipes. Utilizing a Doubly Linked List data structure, the bot navigates through cooking instructions, categorizing each step by associated actions, ingredients, tools, and utensils. This structured approach enables the RecipeBot to provide assistance during cooking by answering user queries in real-time. The implementation hinges on a robust model that interprets each recipe sentence as a potential instruction step, extracting and parsing pertinent details into a cohesive framework. Moreover, the RecipeBot extends its functionality to Slack, where it can be interacted with through dedicated channels, making it an accessible and interactive cooking companion. The project stands out for its practical application of parsing techniques and natural language processing to create a user-oriented solution in an everyday context.',
    role: "In the ParsingProject, I was responsible for developing the RecipeBot using Rasa, a task that involved setting up the necessary files, infrastructure, and knowledge base. My role entailed not only the initial creation of the bot but also the integration of a portion of the actions that allowed for the parsing and processing of cooking instructions. I personally contributed to the bot's interactive features, coding actions that enable users to request specific steps of a recipe and ask for a repetition of instructions, thereby enhancing the user experience and utility of the RecipeBot in practical cooking scenarios.",
    skills: [
      'Rasa',
      'NLP',
      'Python',
      'Rest API',
      'Slack API',
      'Conversational AI',
    ],
  },
  {
    name: 'Operations',
    year: '2023',
    github: 'https://github.com/emkwei/Operations',
    website: null,
    about:
      "For our Operations project, we engineered a modern rendition of the classic board game 'Operation', integrating conductive tweezers, a micro:bit microcontroller, LED lights, and light sensors connected through an I2C bridge to simulate a computer motherboard repair scenario. This interactive game challenges players to extract 'viruses' and 'bugs' from cutouts on a motherboard-themed board. Each successful operation is rewarded with a celebratory tune and a glow from the green LED, while an accidental touch to the cutout edges triggers a red LED alert and an error sound, reflecting the precision required in actual electronic repairs. The removal of these bugs is detected by light sensors, which communicate with the microcontroller via an I2C bridge to ensure accurate gameplay feedback. The entire experience is enhanced with a timed gameplay element, adding to the urgency and excitement of diagnosing and fixing a 'sick' motherboard.",
    role: 'In the operations project, I designed and built the conductive tweezers and the physical game board, mirroring a computer motherboard. I also developed the interface between the I2C bridge and the micro:bit microcontroller, crucial for light sensor communication. My work also extended to assisting my team in programming the sensor interaction to detect the removal of game pieces and implementing the game logic for win/lose conditions. This required skills in hardware integration, software development, and system design, focusing on precise functionality and user interaction.',
    skills: [
      'Hardware design',
      'Microcontroller programming',
      'I2C protocol',
      'Sensor integration',
      'Embedded system',
      'Game design',
    ],
  },
  {
    name: 'TweetMining',
    year: '2023',
    github: 'https://github.com/emkwei/TweetMining',
    website: null,
    about:
      'The Tweet Mining project focuses on analyzing Golden Globes-related tweets to extract meaningful insights into categories, red carpet mentions, hosts, nominees, presenters, and winners. Utilizing Python, Spacy for natural language processing, and custom algorithms for data cleaning and entity merging, the team developed a system to process tweets, identifying significant information with enhanced accuracy through techniques like keyword filtering, entity recognition, and regex pattern matching. The approach includes handling data inconsistencies and leveraging similarity scores for entity consolidation, ultimately outputting categorized results into structured JSON files. This project demonstrates the application of advanced text processing techniques to derive actionable insights from social media data efficiently.',
    role: 'In the Tweet Mining project, I was responsible for writing Python scripts to parse, clean, and extract data from tweets, ensuring high-quality inputs for analysis. I developed custom scripts for targeted entity extraction and performed sentiment analysis, applying natural language processing (NLP) techniques to filter and interpret critical information. Additionally, I supported my teammates by enhancing and troubleshooting their scripts, contributing to the overall efficiency and accuracy of our data analysis workflow. My role emphasized the application of technical skills in data processing and NLP to achieve precise insights into public opinions and trends surrounding the Golden Globes.',
    skills: [
      'NLP',
      'Spacy',
      'Regex',
      'Python',
      'Sentiment Analysis',
      'Entity Recognition',
    ],
  },
  {
    name: 'WildHacks',
    year: '2023',
    github: 'https://github.com/NUWildHacks/website2023',
    website: 'https://www.wildhacks.net/',
    about:
      "WildHacks 2023, Northwestern's standout overnight hackathon, acts as a crucial hub for students eager to sharpen their programming skills, collaborate on forward-thinking projects, and immerse themselves in a rich educational setting. For this event's promotion, we crafted a frontend client using JavaScript with React, ensuring compliance with Major League Hacking (MLH) standards. This setup simplifies the registration process, allowing participants to navigate a custom dashboard efficiently. This year, leveraging Next.js, we created a dashboard to include interactive features such as user authentication, project submission capabilities, and a sophisticated judging algorithm. This platform not only facilitates project submissions but also allows participants to view an assortment of projects from past events, nurturing a space for inspiration and ingenuity. In line with 2023's \"City Lights\" theme, the website features a lively, urban-themed design, offering users an experience that reflects the dynamism and inventiveness of urban environments, thus bridging the gap between urban evolution and technological innovation.",
    role: "As a member of the technology team for WildHacks 2023, my main contribution was working on the frontend client using JavaScript and React. I actively participated in all our meetings, ensuring I was fully engaged in the project's development process. Additionally, I collaborated closely with the Director of Technology to develop the custom dashboard. This included implementing features like user authentication, project submission, and setting up the judging algorithm, all of which were crucial for enhancing the user experience and functionality of our event's website.",
    skills: [
      'JavaScript',
      'React',
      'Next.js',
      'Teamwork',
      'Full-Stack',
      'UI/UX',
    ],
  },
  {
    name: 'ConnectedSpine',
    year: '2023',
    github: 'https://github.com/emkwei/ConnectedSpine',
    website: null,
    about:
      "ConnectedSpine is a web application designed to offer users immediate, personalized recommendations for back pain treatment based on their self-reported symptoms and history. Utilizing React and Bootstrap for a responsive user interface, the app guides users through a detailed questionnaire, culminating in tailored treatment suggestions. Key contributions include the implementation of a dynamic form system capturing user input on back pain conditions, integration with Firebase for data management and authentication, and the deployment of algorithms to analyze responses and generate treatment advice. The project's infrastructure supports future enhancements such as provider recommendations by location, comprehensive user history management, and community feedback mechanisms to validate the app's efficacy and user satisfaction.",
    role: "In our agile software development team, my primary role included organizing meetings to review progress and set forward goals. From a coding perspective, I focused on modularizing the codebase, ensuring that components, styles, and layouts were reusable across different sections of our website. I was solely in charge of developing the login and home pages, along with creating a dynamic question and answer interface and the website's header. Furthermore, I contributed to the development of the questionnaire logic and played a key role in standardizing the format of responses before their submission to our Firebase database. This approach facilitated consistency and efficiency within our project's development process.",
    skills: ['JavaScript', 'React', 'Firebase', 'Agile', 'Vitest', 'Cypress'],
  },
  {
    name: 'PhotoApp',
    year: '2022',
    github: 'https://github.com/emkwei/photo-app',
    website: null,
    about:
      '"PhotoApp" is a full-stack web application I developed, modeled closely after Instagram\'s functionality and architecture. This application was constructed as part of a comprehensive web development course, where I engaged with a wide array of technologies ranging from front-end design using HTML and CSS to building robust web servers and RESTful APIs with Flask. Key features of the application include user authentication, the ability to follow or unfollow accounts, like and unlike posts, and comment on posts, all of which are underpinned by a PostgreSQL database. Throughout the project, accessibility was prioritized, ensuring keyboard navigation and screen reader compatibility through appropriate ARIA attributes. The front end was crafted with React, providing a dynamic and responsive user experience. The application\'s structure is outlined by various components such as NavBar, Profile, Suggestions, and Posts, which collectively form a cohesive and scalable social media platform.',
    role: 'In the creation of the PhotoApp, a full-stack application inspired by Instagram, I was responsible for the end-to-end development, with the exception of the database setup which was provided as a shared demo resource. My tasks encompassed front-end development using React to create a dynamic and interactive user interface, and implementing a Flask server to handle the back-end logic and RESTful API endpoints. I integrated essential features such as user authentication, following/unfollowing functionality, post interactions like liking and commenting, and ensured web accessibility standards were met. I also crafted the front-end components including navigation bars, profile views, and post displays, tying them together into a seamless social media experience. The application logic was meticulously coded in JavaScript, with careful attention to DOM manipulation and AJAX calls for a responsive user experience.',
    skills: [
      'React',
      'Flask',
      'PostgreSQL',
      'Rest API',
      'Heroku',
      'JSON Web Token',
    ],
  },
  {
    name: 'PacMan',
    year: '2022',
    github: 'https://github.com/emkwei/Pac-Man',
    website: null,
    about:
      'In the Pacman project, I leveraged C++ and the GE211 game engine to accurately reproduce the first level of the classic Pacman arcade game. I focused on achieving the precise aspect ratio and dimensional fidelity of the original game. Additionally, I implemented distinct movement algorithms for the ghosts, infusing variable AI personalities into the game dynamics, which was a key aspect of the technical complexity in this recreation.',
    role: "In the Pac-Man project, my primary responsibilities encompassed leveraging C++ and the GE211 game engine to accurately recreate the first level of the classic Pac-Man arcade game, adhering closely to the original's display ratios and proportions. I employed object-oriented design principles to structure the game's architecture, ensuring modular and maintainable code. A significant part of my role involved implementing graphics rendering to bring the game's visuals to life, closely matching the arcade aesthetic. Additionally, I devised pathfinding logic to simulate the distinctive movement patterns and behaviors of the ghosts, each designed with unique characteristics to mimic the original gameplay. This required a deep understanding of game physics and mechanics, which I applied to develop engaging and dynamic game interactions.",
    skills: [
      'C++',
      'GE211',
      'Object-Oriented Design',
      'Graphics',
      'Game Physics',
      'Pathfinding Logic',
    ],
  },
];
